### ISSUE TITLE
Emails for hidden repo does not appear to be sent

### ISSUE THREAD

**Issue by bartkamphorst** [repotag/cutting_edge#65]
Our instance of CuttingEdge has one hidden repo, but update emails do not appear to be sent. One possibility is that the repo's `email` attribute is not used correctly. However, the default email address is also not used.

**Comment by dometto** [comment]
Next time we update a gem we should watch `heroku --logs --tail` to see if the MailWorker throws any errors.

**Comment by dometto** [comment]
The problem was indeed that we did not pass an `email:` argument when initializing the hidden repository. This is now fixed. Ideally, however, `Repository.initialize` would default to the global default email address if nothing were passed. This may be difficult to achieve, since it means making the `Repository` class definition dependent on app settings. Alternatively, we could make the `email: ` argument at least required, so that the user is forced to set it explicitly.

**Comment by bartkamphorst** [comment]
> Alternatively, we could make the email: argument at least required, so that the user is forced to set it explicitly.

I'm not in favor of this. The default is there to fall back on when no deviating address is set. I don't think it's desirable to set the same email for the majority of the defined repos.
